version: '3.8'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
