version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_order_container
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3305:3306"

    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
