version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_inventory_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3304:3306"

    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
